# -*- coding: utf-8 -*-
"""Hormuz_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIN7GSoQ669jazQC3jIKyNx-I5PyBorl
"""

# IMPORT LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import grangercausalitytests

# LOAD DATASET
df = pd.read_csv("/content/Hormuz_Crisis_Dataset.csv", parse_dates=["date"])
df = df.sort_values("date")
df.set_index("date", inplace=True)

# VARIABLES
cols = [
    "daily_ship_transits",
    "oil_throughput_mbpd",
    "lng_throughput_bcfd",
    "brent_crude_usd_bbl"
]

# VISUALIZE RAW SERIES

df[cols].plot(subplots=True, figsize=(10,8), title="Raw Energy System Variables")
plt.show()

# CLEANING
# Replace impossible zero values
df_clean = df[cols].replace(0, np.nan)

# Interpolate missing values
df_clean = df_clean.interpolate()

# Drop remaining NA
df_clean = df_clean.dropna()

# LOG TRANSFORMATION
df_log = np.log(df_clean)

# ADF TEST FUNCTION
def adf_test(series, name):

    result = adfuller(series.dropna())

    print(f"{name}")
    print(f"ADF Statistic : {result[0]:.4f}")
    print(f"P-Value       : {result[1]:.6f}")

    if result[1] < 0.05:
        print("Result        : Stationary")
    else:
        print("Result        : Non-Stationary")

    print("-" * 50)

# STATIONARITY TEST BEFORE DIFFERENCING
print("\n=== BEFORE DIFFERENCING (LOG LEVELS) ===\n")

for c in df_log.columns:
    adf_test(df_log[c], c)

# DIFFERENCING
# Log-difference ≈ percentage shocks
df_diff = df_log.diff().dropna()

# STATIONARITY TEST AFTER DIFFERENCING
print("\n=== AFTER DIFFERENCING (LOG DIFFERENCE SHOCKS) ===\n")

for c in df_diff.columns:
    adf_test(df_diff[c], c)

# SHOCK EVENT TIMELINE
shock_date = "2026-02-28"
plt.figure(figsize=(9, 3))
plt.plot(
    df.index,
    df["brent_crude_usd_bbl"],
    label="Brent Crude Price"
)

plt.axvline(
    pd.Timestamp(shock_date),
    color="red",
    linestyle="--",
    label="Geopolitical Shock"
)

plt.title("Brent Crude Price Around Geopolitical Shock")
plt.legend()
plt.tight_layout()
plt.show()

# VAR Model
model = VAR(df_diff)
lag_order = model.select_order(maxlags=10)
print("\n=== VAR LAG SELECTION ===\n")
print(lag_order.summary())

# SELECTING LAG
# HQIC selected because it balances overfitting and underfitting
best_lag = lag_order.selected_orders["hqic"]

print(f"\nSelected Lag (HQIC): {best_lag}")

# FIT VAR MODEL
results = model.fit(best_lag)

print("\n=== VAR MODEL SUMMARY ===\n")
print(results.summary())

# GRANGER CAUSALITY MATRIX
variables = df_diff.columns

causality_matrix = pd.DataFrame(
    index=variables,
    columns=variables
)

print("\n=== GRANGER CAUSALITY TESTS ===\n")

for cause in variables:

    for effect in variables:

        if cause != effect:

            test_result = grangercausalitytests(
                df_diff[[effect, cause]],
                maxlag=best_lag,
                verbose=False
            )

            # Use ONLY the selected lag p-value
            p_value = test_result[best_lag][0]["ssr_ftest"][1]
            causality_matrix.loc[cause, effect] = round(p_value, 4)
print(causality_matrix)

# INTERPRET SIGNIFICANT CAUSALITY
print("\n=== SIGNIFICANT GRANGER CAUSALITY RELATIONSHIPS ===\n")

for cause in variables:
      for effect in variables:

        if cause != effect:

            pval = float(causality_matrix.loc[cause, effect])

            if pval < 0.05:

                print(
                    f"{cause}  →  {effect} "
                    f"(p-value = {pval:.4f})"
                )

"""Based on the significant Granger Causality Relationships:

Brent Price Is The Dominant Shock Driver as
1. brent → oil throughput
2. brent → LNG throughput
3. brent → ship transits all significant

This means:

Oil price volatility propagates through the entire energy system. Because:
shipping decisions, production volumes, LNG allocation, trade incentives, all react to oil prices.

Shipping Activity Is Reactive, Not Dominant

Based on the significant Granger Causality Relationships: prices → transits

Because in reality:
1. shipping adjusts AFTER market signals,
2. companies reroute dynamically,
3. transport reacts to profitability expectations.

Hence: Shipping disruptions may be more responsive than causative.
"""

# FEVD
# Forecast Error Variance Decomposition
print("\n=== FORECAST ERROR VARIANCE DECOMPOSITION ===\n")
fevd = results.fevd(10)
print(fevd.summary())

# FEVD VISUALIZATION
fig = fevd.plot()
fig.set_size_inches(10, 6)
plt.tight_layout()
plt.show()

"""1. Brent Explains Large Variance Share - This is visible in FEVD.

2. Take Oil Throughput FEVD, at horizon 9: 47% explained by Brent shocks.

Intrepretation:

Oil throughput dynamics are heavily influenced by crude price volatility.

3. Brent Is Relatively Self-Driven

FEVD: ~63% of Brent variance explained by itself.

Oil prices depend on many external global factors:
OPEC, Fed policy, global demand, war risk, USD, speculation.

Hence, the varibles in the dataset cannot fully explain Brent.

4. LNG Is Also Highly Influenced By Brent
"""

# IMPULSE RESPONSE FUNCTIONS
irf = results.irf(15)
fig = irf.plot(orth=True)
fig.set_size_inches(16, 10)
plt.tight_layout()
plt.subplots_adjust(hspace=0.5)
plt.show()

# BRENT SHOCK SPEED METRICS
irf_vals = irf.irfs
brent_idx = df_diff.columns.get_loc(
    "brent_crude_usd_bbl"
)

# Aggregate Brent responses across all shocks
brent_response = np.abs(
    irf_vals[:, :, brent_idx]
).sum(axis=1)

# Peak reaction timing
peak_lag = np.argmax(brent_response)

# Half-life calculation
cumulative = np.cumsum(brent_response)

half_life = np.where(
    cumulative >= 0.5 * cumulative[-1]
)[0][0]

print("\n=== BRENT SHOCK SPEED METRICS ===\n")
print(f"Peak Reaction Lag : {peak_lag}")
print(f"Shock Half-Life   : {half_life}")

"""Interpretation:
  Energy markets react almost immediately to shocks, but approximately half of the shock impact dissipates within 3 periods.

This is economically intitutive as Energy markets are:

1. fast-moving,
2. information-sensitive,
3. globally integrated.
"""

# CUSTOM IRF PLOTS
def plot_irf(impulse, response, title=None, figsize=(7, 4)):

    irf = results.irf(15)

    fig = irf.plot(
        impulse=impulse,
        response=response
    )

    fig.set_size_inches(figsize)

    plt.title(
        title or f"{response} ← {impulse}",
        pad=15
    )

    plt.tight_layout()
    plt.show()

# INTERPRETABLE ECONOMIC CHANNELS
# 1. Logistics disruption channel
plot_irf(
    impulse="daily_ship_transits",
    response="oil_throughput_mbpd",
    title="Transit Shock → Oil Throughput"
)

# 2. LNG supply disruption channel
plot_irf(
    impulse="daily_ship_transits",
    response="lng_throughput_bcfd",
    title="Transit Shock → LNG Throughput"
)

# 3. Energy substitution / interdependence
plot_irf(
    impulse="oil_throughput_mbpd",
    response="lng_throughput_bcfd",
    title="Oil Throughput Shock → LNG Throughput"
)

# 4. Oil market price transmission
plot_irf(
    impulse="oil_throughput_mbpd",
    response="brent_crude_usd_bbl",
    title="Oil Throughput Shock → Brent Crude Price"
)

"""Logistics disruption channel:

1. A disruption in shipping transits initially reduces oil throughput, indicating short-term logistical bottlenecks and transportation inefficiencies. The strongest response occurs around day 3, suggesting delayed propagation of shipping disruptions into oil supply chains. The impact gradually dissipates by days 13–14, implying that the energy transport system eventually absorbs and stabilizes after the shock.

LNG supply disruption channel:

2. LNG throughput initially reacts positively to shipping shocks, possibly reflecting short-term substitution dynamics or inventory adjustments. However, the response quickly turns volatile, with the largest disruption occurring around day 3. This suggests that maritime disruptions significantly affect LNG transport and supply coordination with a delayed effect. The shock gradually fades after days 13–14 as the system adjusts to the disruption.

Energy interdependence / substitution:

3. A shock in oil throughput generates a volatile response in LNG throughput, highlighting interdependence between energy markets. LNG initially declines following oil disruptions, but rebounds sharply during days 2–3, suggesting temporary substitution or adaptive market responses. The subsequent decline around day 4 indicates instability in balancing energy supply adjustments. The shock dissipates after approximately 13–14 days, showing medium-term adjustment within the energy system.

Price transmission channel:

4. Oil throughput shocks generate a delayed response in Brent crude prices. Prices initially decline, potentially reflecting short-term market uncertainty or inventory adjustments, before rising sharply around day 3 as supply constraints become more fully reflected in market pricing. The effect gradually weakens and stabilizes after days 13–14, indicating that global oil markets absorb and normalize the shock over time.
"""

# SHOCK DYNAMICS VISUALIZATION
plt.figure(figsize=(12, 4))
plt.plot(
    df_diff.index,
    df_diff["daily_ship_transits"],
    label="Transit Shock"
)

plt.plot(
    df_diff.index,
    df_diff["brent_crude_usd_bbl"],
    label="Brent Price Shock"
)

plt.title("Shock Dynamics Across Energy System")
plt.legend()
plt.tight_layout()
plt.show()

# VAR DIAGNOSTICS
print("\n=== VAR STABILITY CHECK ===\n")
print("Is VAR Stable?")
print(results.is_stable())

# SERIAL CORRELATION TEST
print("\n=== SERIAL CORRELATION TEST ===\n")
serial_test = results.test_whiteness()
print(serial_test)

# NORMALITY TEST
print("\n=== NORMALITY TEST ===\n")
normality_test = results.test_normality()
print(normality_test)

"""1. Serial Correlation Test:

fail to reject H0 as (p = 0.165)

Residual autocorrelation is NOT significant.

Interpretation: Model captured temporal dynamics reasonably well.

2. Normality Test:

Residuals exhibit non-normality, likely due to volatility clustering and extreme geopolitical shock periods commonly observed in commodity markets.
"""